<?php


 function autoload_87e9c0b78748ec9648f4d37f108d09e2($class)
{
    $classes = array(
        'Clases\Pub_gestdocente' => __DIR__ .'/Pub_gestdocente.php',
        'Clases\wsagrupaciones' => __DIR__ .'/wsagrupaciones.php',
        'Clases\wsagrupacionesResponse' => __DIR__ .'/wsagrupacionesResponse.php',
        'Clases\ArrayOfClaseAgrupaciones' => __DIR__ .'/ArrayOfClaseAgrupaciones.php',
        'Clases\ClaseAgrupaciones' => __DIR__ .'/ClaseAgrupaciones.php',
        'Clases\wsfechaexamenesasi' => __DIR__ .'/wsfechaexamenesasi.php',
        'Clases\wsfechaexamenesasiResponse' => __DIR__ .'/wsfechaexamenesasiResponse.php',
        'Clases\ArrayOfClaseFechaExamenesAsi' => __DIR__ .'/ArrayOfClaseFechaExamenesAsi.php',
        'Clases\ClaseFechaExamenesAsi' => __DIR__ .'/ClaseFechaExamenesAsi.php',
        'Clases\wsfechaexamenesasitotal' => __DIR__ .'/wsfechaexamenesasitotal.php',
        'Clases\wsfechaexamenesasitotalResponse' => __DIR__ .'/wsfechaexamenesasitotalResponse.php',
        'Clases\ArrayOfClaseFechaExamenesAsiTotal' => __DIR__ .'/ArrayOfClaseFechaExamenesAsiTotal.php',
        'Clases\ClaseFechaExamenesAsiTotal' => __DIR__ .'/ClaseFechaExamenesAsiTotal.php',
        'Clases\wsfechaexamenesasinue' => __DIR__ .'/wsfechaexamenesasinue.php',
        'Clases\wsfechaexamenesasinueResponse' => __DIR__ .'/wsfechaexamenesasinueResponse.php',
        'Clases\ArrayOfClaseFechaExamenesAsiNue' => __DIR__ .'/ArrayOfClaseFechaExamenesAsiNue.php',
        'Clases\ClaseFechaExamenesAsiNue' => __DIR__ .'/ClaseFechaExamenesAsiNue.php',
        'Clases\wsfechaexamenesplan' => __DIR__ .'/wsfechaexamenesplan.php',
        'Clases\wsfechaexamenesplanResponse' => __DIR__ .'/wsfechaexamenesplanResponse.php',
        'Clases\ArrayOfClaseFechaExamenesPlan' => __DIR__ .'/ArrayOfClaseFechaExamenesPlan.php',
        'Clases\ClaseFechaExamenesPlan' => __DIR__ .'/ClaseFechaExamenesPlan.php',
        'Clases\wsasidepto' => __DIR__ .'/wsasidepto.php',
        'Clases\wsasideptoResponse' => __DIR__ .'/wsasideptoResponse.php',
        'Clases\ArrayOfClaseAsiDepto' => __DIR__ .'/ArrayOfClaseAsiDepto.php',
        'Clases\ClaseAsiDepto' => __DIR__ .'/ClaseAsiDepto.php',
        'Clases\wsdatosasig' => __DIR__ .'/wsdatosasig.php',
        'Clases\wsdatosasigResponse' => __DIR__ .'/wsdatosasigResponse.php',
        'Clases\ArrayOfClaseDatosAsig' => __DIR__ .'/ArrayOfClaseDatosAsig.php',
        'Clases\ClaseDatosAsig' => __DIR__ .'/ClaseDatosAsig.php',
        'Clases\wshorarioagrp' => __DIR__ .'/wshorarioagrp.php',
        'Clases\wshorarioagrpResponse' => __DIR__ .'/wshorarioagrpResponse.php',
        'Clases\ArrayOfClaseHorarioAgrp' => __DIR__ .'/ArrayOfClaseHorarioAgrp.php',
        'Clases\ClaseHorarioAgrp' => __DIR__ .'/ClaseHorarioAgrp.php',
        'Clases\wshorarios' => __DIR__ .'/wshorarios.php',
        'Clases\wshorariosResponse' => __DIR__ .'/wshorariosResponse.php',
        'Clases\ArrayOfClaseHorarios' => __DIR__ .'/ArrayOfClaseHorarios.php',
        'Clases\ClaseHorarios' => __DIR__ .'/ClaseHorarios.php',
        'Clases\wstitulosuni' => __DIR__ .'/wstitulosuni.php',
        'Clases\wstitulosuniResponse' => __DIR__ .'/wstitulosuniResponse.php',
        'Clases\ArrayOfClaseTitulosUni' => __DIR__ .'/ArrayOfClaseTitulosUni.php',
        'Clases\ClaseTitulosUni' => __DIR__ .'/ClaseTitulosUni.php',
        'Clases\wsdatosplan' => __DIR__ .'/wsdatosplan.php',
        'Clases\wsdatosplanResponse' => __DIR__ .'/wsdatosplanResponse.php',
        'Clases\ArrayOfClaseDatosPlan' => __DIR__ .'/ArrayOfClaseDatosPlan.php',
        'Clases\ClaseDatosPlan' => __DIR__ .'/ClaseDatosPlan.php',
        'Clases\wsplanesasig' => __DIR__ .'/wsplanesasig.php',
        'Clases\wsplanesasigResponse' => __DIR__ .'/wsplanesasigResponse.php',
        'Clases\ArrayOfClasePlanesAsig' => __DIR__ .'/ArrayOfClasePlanesAsig.php',
        'Clases\ClasePlanesAsig' => __DIR__ .'/ClasePlanesAsig.php',
        'Clases\wsplanesdep' => __DIR__ .'/wsplanesdep.php',
        'Clases\wsplanesdepResponse' => __DIR__ .'/wsplanesdepResponse.php',
        'Clases\ArrayOfClasePlanesDep' => __DIR__ .'/ArrayOfClasePlanesDep.php',
        'Clases\ClasePlanesDep' => __DIR__ .'/ClasePlanesDep.php',
        'Clases\wsdptoasig' => __DIR__ .'/wsdptoasig.php',
        'Clases\wsdptoasigResponse' => __DIR__ .'/wsdptoasigResponse.php',
        'Clases\ArrayOfClaseDptoAsig' => __DIR__ .'/ArrayOfClaseDptoAsig.php',
        'Clases\ClaseDptoAsig' => __DIR__ .'/ClaseDptoAsig.php',
        'Clases\wsareasdpto' => __DIR__ .'/wsareasdpto.php',
        'Clases\wsareasdptoResponse' => __DIR__ .'/wsareasdptoResponse.php',
        'Clases\ArrayOfClaseAreasDpto' => __DIR__ .'/ArrayOfClaseAreasDpto.php',
        'Clases\ClaseAreasDpto' => __DIR__ .'/ClaseAreasDpto.php',
        'Clases\wsdptocen' => __DIR__ .'/wsdptocen.php',
        'Clases\wsdptocenResponse' => __DIR__ .'/wsdptocenResponse.php',
        'Clases\ArrayOfClaseDptoCen' => __DIR__ .'/ArrayOfClaseDptoCen.php',
        'Clases\ClaseDptoCen' => __DIR__ .'/ClaseDptoCen.php',
        'Clases\wsasiplan' => __DIR__ .'/wsasiplan.php',
        'Clases\wsasiplanResponse' => __DIR__ .'/wsasiplanResponse.php',
        'Clases\ArrayOfClaseAsiPlan' => __DIR__ .'/ArrayOfClaseAsiPlan.php',
        'Clases\ClaseAsiPlan' => __DIR__ .'/ClaseAsiPlan.php',
        'Clases\wscalificaciones' => __DIR__ .'/wscalificaciones.php',
        'Clases\wscalificacionesResponse' => __DIR__ .'/wscalificacionesResponse.php',
        'Clases\ArrayOfClaseCalificaciones' => __DIR__ .'/ArrayOfClaseCalificaciones.php',
        'Clases\ClaseCalificaciones' => __DIR__ .'/ClaseCalificaciones.php',
        'Clases\wsconvocatorias' => __DIR__ .'/wsconvocatorias.php',
        'Clases\wsconvocatoriasResponse' => __DIR__ .'/wsconvocatoriasResponse.php',
        'Clases\ArrayOfClaseConvocatorias' => __DIR__ .'/ArrayOfClaseConvocatorias.php',
        'Clases\ClaseConvocatorias' => __DIR__ .'/ClaseConvocatorias.php',
        'Clases\wsgruposasi' => __DIR__ .'/wsgruposasi.php',
        'Clases\wsgruposasiResponse' => __DIR__ .'/wsgruposasiResponse.php',
        'Clases\ArrayOfClaseGrupoAsi' => __DIR__ .'/ArrayOfClaseGrupoAsi.php',
        'Clases\ClaseGrupoAsi' => __DIR__ .'/ClaseGrupoAsi.php',
        'Clases\wsconvemovilidad' => __DIR__ .'/wsconvemovilidad.php',
        'Clases\wsconvemovilidadResponse' => __DIR__ .'/wsconvemovilidadResponse.php',
        'Clases\ArrayOfClaseConveMovilidad' => __DIR__ .'/ArrayOfClaseConveMovilidad.php',
        'Clases\ClaseConveMovilidad' => __DIR__ .'/ClaseConveMovilidad.php',
        'Clases\wstitulospropiosuni' => __DIR__ .'/wstitulospropiosuni.php',
        'Clases\wstitulospropiosuniResponse' => __DIR__ .'/wstitulospropiosuniResponse.php',
        'Clases\ArrayOfClaseTitulosPropiosUni' => __DIR__ .'/ArrayOfClaseTitulosPropiosUni.php',
        'Clases\ClaseTitulosPropiosUni' => __DIR__ .'/ClaseTitulosPropiosUni.php',
        'Clases\wsreqidiomab1plan' => __DIR__ .'/wsreqidiomab1plan.php',
        'Clases\wsreqidiomab1planResponse' => __DIR__ .'/wsreqidiomab1planResponse.php',
        'Clases\ClaseReqidiomab1plan' => __DIR__ .'/ClaseReqidiomab1plan.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_87e9c0b78748ec9648f4d37f108d09e2');

// Do nothing. The rest is just leftovers from the code generation.
{
}
